Update realdebrid.py
dreulavelle/iceberg pull request #190
Opened 2024-01-31 12:03 UTC by Pukabyte

- Remove Sample Files From Being Selected
- Only Select Wanted Formats

2024-01-31 12:27 UTC, Gaisberg requested changes
minor comment, looks good.

2024-01-31 12:27 UTC, Gaisberg commented on backend/program/realdebrid.py
>                          if len(wanted_files) > 0 and all(item for item in wanted_files.values() if Path(item["filename"]).suffix in WANTED_FORMATS):
Remove the additional check

2024-02-01 01:10 UTC, dreulavelle commented on backend/program/realdebrid.py
> +        unwanted_keywords = ["sample"]
should do by size instead.. theres too many keywords we'd need to match.. better off cutting off anything under X filesize, which can be set by user. 100mb default.

2024-02-02 04:04 UTC, Pukabyte commented on backend/program/realdebrid.py
>                          if len(wanted_files) > 0 and all(item for item in wanted_files.values() if Path(item["filename"]).suffix in WANTED_FORMATS):
Which do I remove? lol
lines 125 -127?

2024-02-02 04:10 UTC, dreulavelle commented
make sure to pull latest.. I pushed an update to dev

2024-02-03 08:33 UTC, closed without merging